# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "20" }

# Production context
[context.production]
  environment = { NODE_ENV = "production" }

# Test context
[context.test]
  environment = { NODE_ENV = "production" }

# Branch deploy context
[context.branch-deploy]
  environment = { NODE_ENV = "production" }

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to set
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'" 