# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "20" }

# Production context
[context.production]
  environment = { NODE_ENV = "production" }

# Test context
[context.test]
  environment = { NODE_ENV = "production" }

# Branch deploy context
[context.branch-deploy]
  environment = { NODE_ENV = "production" }

# Next.js adapter for Next.js 15
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure Next.js static assets are properly served
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/image*"
  to = "/_next/image:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200
  force = true

# Handle all routes with Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = false

# Headers to set
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 