# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "20" }

# Production context
[context.production]
  environment = { NODE_ENV = "production" }

# Test context
[context.test]
  environment = { NODE_ENV = "production" }

# Branch deploy context
[context.branch-deploy]
  environment = { NODE_ENV = "production" }

# Next.js specific handling
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Required for Next.js routing
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200

# Headers to set
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'" 