name: CI

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['main', 'test']

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint (strict for main branch)
        if: github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.base_ref == 'main')
        run: npm run lint:strict
      
      - name: Lint (relaxed for other branches)
        if: github.ref != 'refs/heads/main' && (github.event_name != 'pull_request' || github.base_ref != 'main')
        run: |
          echo "Using relaxed linting for non-main branch"
          npm run lint
        
      - name: Format check
        run: npx prettier --check "**/*.{js,jsx,ts,tsx,json,md}"
      
      - name: Type check
        run: npm run typecheck
      
      - name: Run tests
        run: npm run test
        
      - name: Check for unused dependencies
        run: npx depcheck 